### ISSUE TITLE
Update Docker Images to latest PHP versions

### ISSUE THREAD

**Issue by westy92** [php-actions/php-build#16]
According to https://github.com/php-actions/php-build/blob/9d8e7cbc5c2e3aa0f5ce00b1930fcc217b5117ff/php-build.bash#L90-L92

PHP version tags like `8.2`, once built, will never be updated to the latest version. As a result, 8.2.0 is available instead of 8.2.18.

Could this be changed so the image is rebuilt if the underlying PHP version is newer?

**Comment by g105b** [comment]
Good catch. Yes, the current behaviour seems to unnecessarily limit the PHP version. I'll check out your PR, thanks.
